---
name: Jordi Arias
email: jariass2@gmail.com 
phone: 649945818
website: www.linkedin.com/in/jordiariassantaella
skills:
  - Team Leadership
  - Business Development
  - Entrepreneurship Development
languages:
  - English (Full Professional)
  - Catalan (Native or Bilingual)
  - French (Professional Working)
  - Spanish (Native or Bilingual)  

experience:
  - company: Fundación Ship2B
    role: Health&Care Lab Manager
    duration: November 2022 - Present
  - company: Freelance
    role: Technology and Corporate Entrepreneurship Expert  
    duration: January 2021 - Present
  - company: IQS Tech Factory
    role: Corporate Venturing Programme promoter and coordinator
    duration: May 2022 - June 2022
  - company: Libroinnovacion.com
    role: Book Co Author
    duration: November 2020 - June 2022
  - company: ACCIÓ
    role: Consultor Acreditado ACCIO en Corporate Venturing y Tecnología
    duration: August 2020 - June 2022
  - company: Hype Corporate Partners  
    role: Managing Partner and Founder
    duration: August 2018 - January 2021
  - company: Mobile World Capital Barcelona
    role: Tech Transfer Manager  
    duration: March 2016 - December 2017
  - company: ACCIÓ
    role: New Technology Based Companies and Aerospace Companies Cluster Manager
    duration: November 2009 - March 2016
  - company: DURERO PACKAGING
    role: Chief Operations Manager
    duration: January 2006 - May 2009
  - company: Industrias Laubat
    role: Chief Technical Officer
    duration: 2002 - January 2005
  - company: TE Connectivity
    role: Engineering Manager
    duration: 1999 - 2002
  - company: CELSA GROUP  
    role: Process Engineering Manager
    duration: 1996 - 1999
  - company: Samsung electronics
    role: Process Engineering Manager
    duration: 1995 - 1997
  - company: Kao Corporation
    role: Production Manager  
    duration: 1990 - 1993

education:
  - institution: ESADE Business School
    degree: Master of Business Administration - MBA
    duration: 1999 - 2002
  - institution: Universitat Politècnica de Catalunya
    degree: Master of Science (M.Sc.), Telecommunications Engineering
    duration: 1993 - 1995
  - institution: Universitat Politècnica de Catalunya
    degree: Bachelor of Science (B.Sc.), Industrial Electronics Engineering
    duration: 1987 - 1990
  - institution: IESE Business School - University of Navarra
    degree: Estrategia
    duration: 2013